// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service/data-source/data_source.proto

package go_micro_srv_data_source

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryDataRequest struct {
	DsType               string   `protobuf:"bytes,1,opt,name=ds_type,json=dsType,proto3" json:"ds_type,omitempty"`
	DsCode               string   `protobuf:"bytes,2,opt,name=ds_code,json=dsCode,proto3" json:"ds_code,omitempty"`
	Params               string   `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	RawData              string   `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	XParentSwiftNumber   string   `protobuf:"bytes,5,opt,name=_parent_swift_number,json=ParentSwiftNumber,proto3" json:"_parent_swift_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDataRequest) Reset()         { *m = QueryDataRequest{} }
func (m *QueryDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDataRequest) ProtoMessage()    {}
func (*QueryDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_305e613822c7bc44, []int{0}
}

func (m *QueryDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDataRequest.Unmarshal(m, b)
}
func (m *QueryDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDataRequest.Marshal(b, m, deterministic)
}
func (m *QueryDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataRequest.Merge(m, src)
}
func (m *QueryDataRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDataRequest.Size(m)
}
func (m *QueryDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataRequest proto.InternalMessageInfo

func (m *QueryDataRequest) GetDsType() string {
	if m != nil {
		return m.DsType
	}
	return ""
}

func (m *QueryDataRequest) GetDsCode() string {
	if m != nil {
		return m.DsCode
	}
	return ""
}

func (m *QueryDataRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *QueryDataRequest) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *QueryDataRequest) GetXParentSwiftNumber() string {
	if m != nil {
		return m.XParentSwiftNumber
	}
	return ""
}

type QueryDataResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	CostTime             int32    `protobuf:"varint,4,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDataResponse) Reset()         { *m = QueryDataResponse{} }
func (m *QueryDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDataResponse) ProtoMessage()    {}
func (*QueryDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_305e613822c7bc44, []int{1}
}

func (m *QueryDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDataResponse.Unmarshal(m, b)
}
func (m *QueryDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDataResponse.Marshal(b, m, deterministic)
}
func (m *QueryDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataResponse.Merge(m, src)
}
func (m *QueryDataResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDataResponse.Size(m)
}
func (m *QueryDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataResponse proto.InternalMessageInfo

func (m *QueryDataResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryDataResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *QueryDataResponse) GetCostTime() int32 {
	if m != nil {
		return m.CostTime
	}
	return 0
}

type QueryParamsRequest struct {
	DsType               string   `protobuf:"bytes,1,opt,name=ds_type,json=dsType,proto3" json:"ds_type,omitempty"`
	DsCode               string   `protobuf:"bytes,2,opt,name=ds_code,json=dsCode,proto3" json:"ds_code,omitempty"`
	XParentSwiftNumber   string   `protobuf:"bytes,5,opt,name=_parent_swift_number,json=ParentSwiftNumber,proto3" json:"_parent_swift_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_305e613822c7bc44, []int{2}
}

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

func (m *QueryParamsRequest) GetDsType() string {
	if m != nil {
		return m.DsType
	}
	return ""
}

func (m *QueryParamsRequest) GetDsCode() string {
	if m != nil {
		return m.DsCode
	}
	return ""
}

func (m *QueryParamsRequest) GetXParentSwiftNumber() string {
	if m != nil {
		return m.XParentSwiftNumber
	}
	return ""
}

type Params struct {
	Params               map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Must                 []string          `protobuf:"bytes,2,rep,name=must,proto3" json:"must,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_305e613822c7bc44, []int{3}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Params) GetMust() []string {
	if m != nil {
		return m.Must
	}
	return nil
}

type QueryParamsResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Params               *Params  `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	CostTime             int32    `protobuf:"varint,4,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_305e613822c7bc44, []int{4}
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryParamsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *QueryParamsResponse) GetCostTime() int32 {
	if m != nil {
		return m.CostTime
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryDataRequest)(nil), "go.micro.srv.data_source.QueryDataRequest")
	proto.RegisterType((*QueryDataResponse)(nil), "go.micro.srv.data_source.QueryDataResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "go.micro.srv.data_source.QueryParamsRequest")
	proto.RegisterType((*Params)(nil), "go.micro.srv.data_source.Params")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.data_source.Params.ParamsEntry")
	proto.RegisterType((*QueryParamsResponse)(nil), "go.micro.srv.data_source.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("proto/service/data-source/data_source.proto", fileDescriptor_305e613822c7bc44)
}

var fileDescriptor_305e613822c7bc44 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x93, 0x34, 0x93, 0x4b, 0x33, 0x54, 0xb0, 0x84, 0x4b, 0xe4, 0x53, 0x44, 0x5b,
	0x47, 0x0a, 0x97, 0xc2, 0x95, 0x72, 0x45, 0xc5, 0xe9, 0xdd, 0xda, 0xc6, 0xd3, 0xca, 0x22, 0xce,
	0x9a, 0x9d, 0xdd, 0x44, 0xe6, 0x5d, 0xe0, 0xcc, 0xab, 0xf1, 0x16, 0xc8, 0xbb, 0x76, 0x94, 0x20,
	0x95, 0xb6, 0x39, 0xed, 0xcc, 0x7e, 0x33, 0xfa, 0xe6, 0x9b, 0x1f, 0x38, 0x2b, 0xb4, 0x32, 0x6a,
	0xca, 0xa4, 0xd7, 0xd9, 0x82, 0xa6, 0xa9, 0x34, 0xf2, 0x82, 0x95, 0xd5, 0xb5, 0x9d, 0x78, 0x3b,
	0x72, 0x51, 0x28, 0xee, 0x55, 0x94, 0x67, 0x0b, 0xad, 0x22, 0xd6, 0xeb, 0x68, 0x07, 0x0f, 0x7f,
	0x07, 0x70, 0xf2, 0xd5, 0x92, 0x2e, 0xaf, 0xa4, 0x91, 0x31, 0x7d, 0xb7, 0xc4, 0x06, 0x5f, 0x43,
	0x2f, 0xe5, 0xc4, 0x94, 0x05, 0x89, 0x60, 0x1c, 0x4c, 0xfa, 0x71, 0x37, 0xe5, 0x9b, 0xb2, 0xa0,
	0x1a, 0x58, 0xa8, 0x94, 0x44, 0xab, 0x01, 0x3e, 0xa9, 0x94, 0xf0, 0x15, 0x74, 0x0b, 0xa9, 0x65,
	0xce, 0xa2, 0xed, 0xff, 0xbd, 0x87, 0x6f, 0xe0, 0x58, 0xcb, 0x4d, 0x52, 0x31, 0x8a, 0x23, 0x87,
	0xf4, 0xb4, 0xdc, 0x54, 0x5c, 0x38, 0x85, 0xd3, 0xa4, 0x90, 0x9a, 0x56, 0x26, 0xe1, 0x4d, 0x76,
	0x67, 0x92, 0x95, 0xcd, 0x6f, 0x49, 0x8b, 0x8e, 0x0b, 0x1b, 0x5e, 0x3b, 0x68, 0x5e, 0x21, 0x5f,
	0x1c, 0x10, 0xfe, 0x80, 0xe1, 0x4e, 0xa5, 0x5c, 0xa8, 0x15, 0x3b, 0x62, 0x36, 0xd2, 0x58, 0x76,
	0x95, 0x76, 0xe2, 0xda, 0x43, 0x01, 0xbd, 0x9c, 0x98, 0xe5, 0x7d, 0x53, 0x69, 0xe3, 0x56, 0x19,
	0x9a, 0xd8, 0x2e, 0x4d, 0x53, 0xaa, 0xf7, 0xf0, 0x2d, 0xf4, 0x17, 0x8a, 0x4d, 0x62, 0xb2, 0x9c,
	0x5c, 0xad, 0x9d, 0xf8, 0xb8, 0xfa, 0xb8, 0xc9, 0x72, 0x0a, 0x37, 0x80, 0x8e, 0xfb, 0xda, 0xc9,
	0x3a, 0xbc, 0x4f, 0xcf, 0x16, 0xfd, 0x33, 0x80, 0xae, 0x27, 0xc5, 0xab, 0x6d, 0x8f, 0x83, 0x71,
	0x7b, 0x32, 0x98, 0x9d, 0x47, 0x0f, 0x4d, 0x35, 0xf2, 0x19, 0xf5, 0xf3, 0x79, 0x65, 0x74, 0xb9,
	0x9d, 0x08, 0xc2, 0x51, 0x6e, 0xd9, 0x88, 0xd6, 0xb8, 0x3d, 0xe9, 0xc7, 0xce, 0x1e, 0x7d, 0x80,
	0xc1, 0x4e, 0x28, 0x9e, 0x40, 0xfb, 0x1b, 0x95, 0xb5, 0xa4, 0xca, 0xc4, 0x53, 0xe8, 0xac, 0xe5,
	0xd2, 0x36, 0x6a, 0xbc, 0xf3, 0xb1, 0x75, 0x19, 0x84, 0xbf, 0x02, 0x78, 0xb9, 0xd7, 0x99, 0x83,
	0xe7, 0x72, 0xb9, 0xb7, 0x42, 0x83, 0xd9, 0xf8, 0x31, 0x79, 0x5b, 0x49, 0xff, 0x9b, 0xdc, 0xec,
	0x4f, 0x00, 0xc3, 0x6a, 0x63, 0xe6, 0x2e, 0x75, 0xee, 0xcf, 0x05, 0xef, 0xa0, 0xbf, 0xdd, 0x25,
	0x7c, 0xf7, 0x30, 0xd3, 0xbf, 0xa7, 0x31, 0x3a, 0x7b, 0x52, 0xac, 0x6f, 0x42, 0xf8, 0x02, 0x97,
	0x30, 0xd8, 0xe9, 0x0e, 0x9e, 0x3f, 0x92, 0xbd, 0xb7, 0x5e, 0xa3, 0x8b, 0x27, 0x46, 0x37, 0x6c,
	0xb7, 0x5d, 0x77, 0xed, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x60, 0xe3, 0xd7, 0x1c,
	0x04, 0x00, 0x00,
}
